"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from split_settings.tools import include

components = [
    "app",
    "base",
    "cors",
    "db",
    "debug",
    # "djoser",
    "installed_apps",
    "logging",
    "media",
    "middleware",
    "oas3",
    "rest",
    "static",
    "storages",
    "templates",
]
base_settings = map(lambda x: "%s.py" % x, components)
include(*base_settings)
